### ISSUE TITLE
Not working properly?

### ISSUE THREAD

**Issue by samsilly12345** [Hexxah/CoC-MOD-Android-Build#7] opened 2018-08-21 06:45 UTC
Hello there is no instructions on how to download this correct, what the x86 or whatever apk is for, or anything like that so I don't know if I'm doing it wrong or not.

But the x86 file will not download on my phone, it calls it an update and it install and then when it's done it says "app not installed" I've tried several times.

And also I used the arm apk and it works. Sorta. It looks and acts like it's on the website browser version of CoC instead of an app or Android version. And as such is very small and no matter how I turn my phone it won't full screen or adjust the size of the window. And also it makes scrolling incredibly hard to do, I can't zoom in or anything like I would be able to if I just used my phone's browser to play it. 

Help!!! Is it supposed to look like that? Is it supposed to act like that? Fix please! Help me fix it!

**Comment by DragonessLover** [comment] 2018-08-21 08:25
Most Android devices will use the arm APKs, just ignore the x86 APKs and the SWFs, you can go into the settings menu of the game to adjust the text size, unfortunately, you are stuck with the tiny scroll bar, as for getting it full screen, make sure you rotate your phone before you open the app or after it fully loads, DO NOT TURN THE PHONE WHILE THE APP IS LOADING

**Comment by samsilly12345** [comment] 2018-08-21 08:35
I've tried and done all of that, and no matter what I do, even if I've waited for it to load, it stays a very small window within my screen and I cannot zoom in or make it the size fullscreens should be. It is very very very much only a little bit bigger when I rotate my phone. It makes it very very very hard to see scroll or press buttons accurately @dragonesslover

**Comment by DragonessLover** [comment] 2018-08-21 09:10
What kind of phone do you have?

**Comment by samsilly12345** [comment] 2018-08-21 09:15
@dragonesslover a Google pixel XL

**Comment by DragonessLover** [comment] 2018-08-21 09:20
Hmm... I can't think of any reason you'd be having these issues, hopefully, @Hexxah can help

**Comment by Oxdeception** [comment] 2018-08-21 10:52
Please post a screenshot of this.

**Comment by samsilly12345** [comment] 2018-08-22 04:24
@oxdeception is there a way to post screenshots or pictures on mobile? Would I need to do it in the discord chat?

**Comment by Orion0132** [comment] 2018-08-22 17:07
@samsilly12345 You could upload the image to Imgur and share the link, like this: http://imgur.com/GczqduT    landscape. 
http://imgur.com/wAkG1Yz   portrait. 
This is with my phone (Sony xperia xa1 ultra)

**Comment by Oxdeception** [comment] 2018-08-22 18:36
I apologize for the delay, I never got a notification for the previous message.
You could use @Orion0132 's suggestion, or attempt to do this by requesting the desktop version of the site on your phone.

**Comment by Hexxah** [comment] 2018-08-23 05:54
First off x86 version is for mainly phones/tablets with Intel processors, arm would be for snapdragon processor like found in pixel phones. 

Secondly screen size issue, if squished try rotating your phone to portrait and back to landscape. 
If you mean the black bars on the side, can't really fix that since its hard coded into CoC as it was originally made for desktops and uses 800x600 which is squareish compared to the widescreen found in our phones.

Scrolling and touch again back to it being made for desktop and flash is quite legacy, it was never made for touch. This apk just creates a nice wrapper to load the swf and easily access saves.

P.S. I am using Essential Phone, so it's pretty much same specs as you pixel and is fine with mine, jus pressing some buttons is a PITA.

**Comment by Oxdeception** [comment] 2018-08-23 11:39
Attached image as posted in the Discord, for future reference.

![screenshot_20180822-002806](https://user-images.githubusercontent.com/30361731/44523168-f7625a00-a6a6-11e8-863e-6027258e1545.png)

This is expected behaviour, so I'll be closing this issue. Changing this would require changing the game's code, currently.

**Closed as completed by Oxdeception** 2018-08-23 11:39 UTC
Labels: question
